create table SoFar_Highest
(
id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
datasource varchar2(50),
metric_name varchar2(50),
sofar_highest number(10,2),
sofar_highest_timestamp date,
prev_sofar_highest number(10,2),
prev_sofar_highest_timestamp date,
constraints unique_soFarHighest unique(datasource, metric_name),
constraints pk_soFarHighest primary key(id)
)